[project]
name = "stacks-spr"
description = "Claim-based Spray/Airdrop contract for Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"

# Main contracts
[contracts.spray-token]
path = "contracts/spray-token.clar"
clarity_version = 3
epoch = "3.0"

[contracts.spray]
path = "contracts/spray.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["spray-token"]

# Test contracts
[contracts.spray_test]
path = "tests/spray_test.clar"
clarity_version = 3
epoch = "3.0"
depends_on = ["spray", "spray-token"]

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
